### PR TITLE
Add: European Portuguese

### PR DESCRIPTION
**Pull request by ReduxFlakes**
Hi, as promised, here is the Portuguese translation. By the way, fantastic project. If there's a new change, just contact me and I will be glad to update it.

### CODE REVIEW

**Comment by Ilithy** [comment]
thank you very much, it was extremely fast and it's very kind of you, thank you again <3

**Comment by ReduxFlakes** [comment]
I've updated the strings from the latest commit

**Comment by ReduxFlakes** [comment]
I've updated the app translation with the latest commits and I also added the metadata

**Comment by jooooscha** [comment]
Thank sou so much. I will merge this later today

**Pull request merged**
