### PR TITLE
Optimize language files

### PR DESCRIPTION
**Pull request by Ilithy**
- Optimization: removal of useless elements _(still present)_ like `translatable="false"` info, addition of line break _(to follow the reference file)_.

- Addition: Added missing strings _(compared to the reference file)_ to be translated in language files

### CODE REVIEW

**Comment by jooooscha** [comment]
@Ilithy Did you see my review?

**Comment by Ilithy** [comment]
@jooooscha No I don't see her, sorry

**Comment by jooooscha** [comment]
Can you resolve the error from the review? I am not sure when I will have time for it

**Comment by Ilithy** [comment]
I don't see any reviews on the modified files, otherwise yes I am quite willing to work on it :)

**Comment by jooooscha** [comment]
You can see my review in this thread a few messages up

**Comment by Ilithy** [comment]
> You can see my review in this thread a few messages up

Sorry, I understood that you had reviewed the files and left me a comment.

Yes, I will take care of that.

**Pull request merged**
