### PR TITLE
Optimize strings.xml

### PR DESCRIPTION
**Pull request by R7010A**
Optimized german strings.
Hope  I made all right here on github cuz it is my first time to create a pull request ... ;-)

### CODE REVIEW

**Comment by jooooscha** [comment]
Yes, you made everything correct :)

Thank you very much

**Comment by R7010A** [comment]
why is line 22 <string name="swipe_left_app">App öffnen (links wischen)</string> not merged?
It is similar to line 23.
Cheers

**Comment by jooooscha** [comment]
I am no sure what you mean?
If you look at the file on the main branch, your changes have all been adpted

**Comment by R7010A** [comment]
Sorry my fault.
I looked at my first (wrong) pull request here: https://github.com/jooooscha/Olauncher/pull/75/commits/b7130402f621d9d7b81c8711afd333860515d2c6

I checked the main branch and all is fine. 
Thank you.

**Pull request merged**
