### PR TITLE
 Update Persian!

### PR DESCRIPTION
**Pull request by mojienjoyment**
Update Persian!

### CODE REVIEW

**Comment by jooooscha** [comment]
There have also been a number of other changes to the original strings.xml. Is there any chance you could update them too?

**Comment by mojienjoyment** [comment]
> There have also been a number of other changes to the original strings.xml. Is there any chance you could update them too?

Oh!  I didn't see it. Update it soon

**Comment by mojienjoyment** [comment]
> There have also been a number of other changes to the original strings.xml. Is there any chance you could update them too?

Updated and ready! but one thing...
I see "Commit" string in my string language file but not found on original string file..

**Comment by Ilithy** [comment]
@mojienjoyment it's a small oversight, I correct it immediately, it was replaced by @jooooscha by "save"

**Comment by jooooscha** [comment]
Is this ready to be merged then?

**Comment by Ilithy** [comment]
@jooooscha Yes indeed, thanks.

**Pull request merged**
