### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by quxup**
The Estonian translation. Sentence structure slightly changed to work with the Estonian language structure which has different rules.

### CODE REVIEW

**Comment by Ilithy** [comment]
Hello and thank you very much for this excellent contribution, but there are several problems, no worries, it will be solved ;-)

- your translation (the translated strings.xml file) must be in a specific folder in `res/values-et/strings.xml`

- You MUST NOT modify the strings.xml file present in the `res/values/` folder

- If possible, translate the short_description and full_description files present in [this folder](https://github.com/quxup/Olauncher/tree/patch-1/fastlane/metadata/android/en-US)
(you have to create them in a folder in `fastlane/metadata/android/`
name et-ET)

If you need more info or help, don't hesitate to let me know.

I will make some changes to your Fork to facilitate the work of @jooooscha (the owner/developer)

thank you so much

**Comment by Ilithy** [comment]
#### Translation checklist

Here is a list of things that can be translated.
Not all of them are strictly needed.

- [X] I have translated the strings.xml
- [ ] I have translated the short_description.md
- [ ] I have translated the full_description.md
- [X] I have added the langage to the language list in the README
- [ ] I have added the langage to the language list in the full_description.md

#### Integration checklist

If you add a new translation there are some things that need to be added to the code.
If you know how, here is a checklist of things that need to be done.

- [X] Add the language to the `Language` enum in `app/src/main/java/app/olaunchercf/data/Constants.kt` (Please use the english name here)
- [X] Add the **native name** of the language to the `string()` method of the `Language` enum. (For example for `German` add `Deutsch`, for `Persian` add `فارسی`)
- [X] Add the country code to the `value()` method of the `Language` enum.

**Comment by jooooscha** [comment]
It this ready to be merged?

**Comment by Ilithy** [comment]
> It this ready to be merged?

Yes, except for this conflict in the constants.kt file

**Pull request merged**
