### PR TITLE
add persian translation

### PR DESCRIPTION
**Pull request by mojienjoyment**
add persian translation

### CODE REVIEW

**Comment by Ilithy** [comment]
_Thank you very much for this translation (extremely fast)_

**Comment by jooooscha** [comment]
Thank you very much for your work.

I have just merged #30, which introduces some changed and some new strings. Could you rebase your commits on main, or give me access to your repo?

**Comment by mojienjoyment** [comment]
> Thank you very much for your work.
> 
> I have just merged #30, which introduces some changed and some new strings. Could you rebase your commits on main, or give me access to your repo?
> 
> You could also add the entry to the readme and the description file in fastlane/metadata/android/en-US/full_description.txt. This way, that would all be together in one commit :)

Great!

I use "fetch and upstream" from main. Is it okey?
I added Persian to full_description.txt.
And I Try to give access to my repo....
Is it okey?

**Comment by jooooscha** [comment]
yes perfect 👍

**Pull request merged**
