### PR TITLE
Create strings.xml

### PR DESCRIPTION
**Pull request by orestisfra**
Greek locale

### CODE REVIEW

**Comment by jooooscha** [comment]
I will add this to the settings and merge afterwards, as soon as I have time

**Comment by jooooscha** [comment]
I have done some changes, but I cannot push to your branch. Could you give me access rights to it?

**Comment by jooooscha** [comment]
Also there are some issues as the Greek translation are much longer than the original English ones. You think this could be fixed, by changing the translation?

image

**Comment by orestisfra** [comment]
> I have done some changes, but I cannot push to your branch. Could you give me access rights to it?

I have added you to orestisfra/Olauncher, if this is what you mean. I am fairly new to github so feel free to guide me if I get something wrong. If there is a way to make everyone here have access please tell me. 

> Also there are some issues as the Greek translation are much longer than the original English ones. You think this could be fixed, by changing the translation?

It's true that the Greek language does not translate exactly from English so the translation tends to be wordier. For example there is no word for "privacy" and no short forms of "on" and "off". There are translations though. I'll try to fix it for sure. This looks unusable.

**Comment by jooooscha** [comment]
Yes, thank you. I should have access now (cant confirm atm)

To the translation: See what you can do. Otherwise, I think the settings design certainly could be improved a lot. This will take time, but then I could make it more adaptable for longer texts

**Comment by orestisfra** [comment]
I made some changes. please check them out at your earliest convenience and tell me how it looks.

**Comment by jooooscha** [comment]
image

Your changes helped a lot. Only one is still overlapping. Anything you can do about it?

**Comment by jooooscha** [comment]
Great. I have opened #58. If that is fixed, you might have more freedom in the tanslation :)

**Comment by jooooscha** [comment]
Look good to me

**Comment by jooooscha** [comment]
I have merge #30 which allows for longer texts. If you are not happy with the current translation, you could now try to use the original versions, again

**Pull request merged**
