### PR TITLE
Readme rework

### PR DESCRIPTION
**Pull request by jooooscha**

### CODE REVIEW

**Comment by jooooscha** [comment]
Wow you are doing just a great job. Thank you very.

I have a few thoughts, but please note that these are all very minor, and only meant as suggestions.

- Your new header image look awesome, I only think we should have one screenshot, that shows the complete home screen, with clock and date. I like, however, how the phone goes over into the two parts of the image.
- As said in the first point, I like how the phone is separated into the two parts of the image, I am not sure, however, how this looks in the f-droid screenshots. I you look at how the images are displayed in the f-droid apps, all images are shown separately, so the effect would not working there.


I want to underline again, that those are only my personal opinions. I give you the last word to decide how the images should look :)

**Comment by Ilithy** [comment]
I changed the presentation captures of the stores, to get closer to what you asked me (rightly); in additional modification I allowed myself to remove the titles (which I find useless for stores), identically if you have changes, let me know, I would do according.

**Comment by jooooscha** [comment]
Thank you very much. This looks awesome.

Did you see my review on the permissions?

**Comment by Ilithy** [comment]
Yes I have seen them, and it looks much cleaner and organized this way, clearly I prefer with your modifications

For the app store captures, I'm not totally satisfied with my work yet, but it's a start

**Review by jooooscha — COMMENTED** [review]
I am not sure the privacy policy is needed or helpful. We already have a license and the permissions state that we do have internet permissions. This makes it impossible to collect user data anyway.
Having a complete privacy policy seems more like "we could collect data, but we wont. I promise".

I particularly don't like the "Changes to this Policy" part. This sounds like we "promise this for now, but if you have to re-read this with every release." The users should download this software and be sure it does not track you in any way, ever.

Therefore I would stick to the explanation of permissions in the README, but not add a privacy policy.

**Comment by jooooscha** [comment]
For the new header text, I like the style but as it is an image, it does not look good when github is in darkmode. I would stick to text here. What do you think?

**Comment by Ilithy** [comment]
@jooooscha, for the privacy policy I got carried away ;-) it's more in case the app would be posted on the Play Store (which requires one), if you don't like it, you're right delete, it does not bother me. :)
Thank you for asking me the question, and giving me your opinion explicitly. 🙏

For the image, sorry I use very bright nano led screens I had not seen it that way, yes obviously you are also right on this point, to be deleted (I would surely make other proposals if you are Okay)

**Comment by jooooscha** [comment]
The problem is that images will always look bad either on light-mode or dark-mode. I would keep it simple and stick to a text header.

You definitely have a point with the playstore and the privacy policy. But I currently I don't plan to upload this fork to the play store, therefore I would, for the moment, not have one.

**Comment by Ilithy** [comment]
> The problem is that images will always look bad either on light-mode or dark-mode. I would keep it simple and stick to text. (This also makes your header image stick out more :) )
> 

I was thinking more of a "full" image on a non-transparent background (like the header of this [readme](https://github.com/OpenLauncherTeam/openlauncher)), but I hear your decision and won't offer you another one as a replacement, sorry to disrupt you with that.

> You definitely have a point with the playstore and the privacy policy. But I currently I don't plan to upload this fork to the play store, therefore I would, for the moment, not have one.

I understand without any problem, there is already enough

**Comment by jooooscha** [comment]
Yes that example does look a lot better, but I think it would clash with thr header image!?

I'd say we should not make it more complicated than neccasarry 🤷‍♂️

Anyway, I realy like you header image, so thank you a lot for you work. I really appreciate it :)

**Comment by jooooscha** [comment]
Sure, if that is not too much work for you :)

**Comment by Ilithy** [comment]
> Sure, if that is not too much work for you :)

Absolutely not, in fact it's already been done.
I took the opportunity to do the same with the Fdroid presentation

**Comment by jooooscha** [comment]
This look very thank. Thank you very much.

Only one thing, could you downscale the image a bit? It took a long time to load. I think a resolution of about 1080x720 should suffice

**Comment by Ilithy** [comment]
> This look very thank. Thank you very much.
> 
> Only one thing, could you downscale the image a bit? It took a long time to load. I think a resolution of about 1080x720 should suffice

it is true that I abused on the resolution of this image (7180*3600), on the other hand the closest resolution to that which you ask me and the 1080*541 (to respect the proportions of the image), it makes 688Ko, I upload it? where should it be adjusted? (in resolution, weight or other)

**Comment by jooooscha** [comment]
Maybe orientade on the original image? its 720 in height with 300 dpi

**Comment by jooooscha** [comment]
Yes that is a lot better :)

**Comment by Ilithy** [comment]
yes and the elements being separated, the weight will be more easily eliminated, I take care of it, and make you an honest proposal ;-)

**Comment by Ilithy** [comment]
Please, it's normal; yes, that seems fine to me.

**Pull request merged**
