### PR TITLE
Add korean translation

### PR DESCRIPTION
**Pull request by Sannoob3144**

### CODE REVIEW

**Comment by jooooscha** [comment]
Thank you so much. Just wantet to point out that you did translate 'clutter free' for the short description, but not in the `strings.xml`.

**Comment by jooooscha** [comment]
I am sorry, what do you want me to review?

**Comment by jooooscha** [comment]
Do you mean the new commits? Looks good to me. But there is still an open review, do you see that? I have commented on line 4 of the full_description

**Comment by Sannoob3144** [comment]
Looks good to me too :)

**Pull request merged**
